apiVersion: v1
kind: Service
metadata:
  name: skill-nest-backend-service
  namespace: skill-nest
spec:
  selector:
    app: skill-nest-backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP

